require "prototypes/item-groups"
require "prototypes/recipe-categories"

require "prototypes/pipes/ht-pipes"

-- (( Circuit Connector Definitions )) --
require "prototypes/circuit-connector-definitions"
-- ))

--(( Technology ))--
require "prototypes/technologies/aerogel"
require "prototypes/technologies/auog"
require "prototypes/technologies/basic-electronics"
require "prototypes/technologies/biopolymer"
require "prototypes/technologies/biotech"
require "prototypes/technologies/cadaveric-arum"
require "prototypes/technologies/carbon-nanotube"
require "prototypes/technologies/ceramic"
require "prototypes/technologies/collagen"
require "prototypes/technologies/colloidal-silica"
require "prototypes/technologies/earnshaw-theorem"
require "prototypes/technologies/electronics-machines"
require "prototypes/technologies/epoxy"
require "prototypes/technologies/ethylene"
require "prototypes/technologies/fertilizer"
require "prototypes/technologies/fiberboard"
require "prototypes/technologies/fiberglass"
require "prototypes/technologies/graphene"
require "prototypes/technologies/ht-robotics"
require "prototypes/technologies/integrated-circuits"
require "prototypes/technologies/kicalk"
require "prototypes/technologies/magnetic-core"
require "prototypes/technologies/melamine"
require "prototypes/technologies/microfibers"
require "prototypes/technologies/moondrop"
require "prototypes/technologies/mukmoux"
require "prototypes/technologies/quantum-processor"
require "prototypes/technologies/nems"
require "prototypes/technologies/nitrobenzene"
require "prototypes/technologies/nucleo"
require "prototypes/technologies/nylon"
require "prototypes/technologies/paramagnetic-material"
require "prototypes/technologies/parametric-oscilator"
require "prototypes/technologies/phenol"
require "prototypes/technologies/phosphorous-processing"
require "prototypes/technologies/plastics"
require "prototypes/technologies/propene"
require "prototypes/technologies/space-science-pack"
require "prototypes/technologies/rare-earth-tech"
require "prototypes/technologies/rayon"
require "prototypes/technologies/re-magnet"
require "prototypes/technologies/semiconductor-doping"
require "prototypes/technologies/supercapacitor"
require "prototypes/technologies/superconductor"
require "prototypes/technologies/ulric"
require "prototypes/technologies/electronics"
require "prototypes/technologies/zipir"
require "prototypes/technologies/zno-nanoparticles"

--(( ORES ))--
require "prototypes/ore/phosphate-rock"
require "prototypes/ore/rare-earth-bolide"

--(( RECIPES ))--
require "prototypes/recipes/recipes"
require "prototypes/recipes/recipes-particle"
require "prototypes/recipes/fluids"

--(( ITEMS ))--
require "prototypes/items/items"
require "prototypes/items/buildings"
require "prototypes/items/trains"

--(( ROBOTS ))--
require "prototypes/robots/py-construction-robot-mk04"
require "prototypes/robots/py-logistic-robot-mk04"

--(( BUILDINGS ))--
require "prototypes/buildings/phosphate-mine"
require "prototypes/buildings/rare-earth-mine"
require "prototypes/buildings/aoug-paddock"
require "prototypes/buildings/kicalk-plantation"
require "prototypes/buildings/zipir"
require "prototypes/buildings/clay-pit"
require "prototypes/buildings/moondrop-greenhouse-mk01"
require "prototypes/buildings/fbreactor-mk01"
require "prototypes/buildings/fbreactor-mk02"
require "prototypes/buildings/fbreactor-mk03"
require "prototypes/buildings/fbreactor-mk04"
require "prototypes/buildings/electronics-factory-mk01"
require "prototypes/buildings/electronics-factory-mk02"
require "prototypes/buildings/electronics-factory-mk03"
require "prototypes/buildings/electronics-factory-mk04"
require "prototypes/buildings/pulp-mill-mk01"
require "prototypes/buildings/pulp-mill-mk02"
require "prototypes/buildings/pulp-mill-mk03"
require "prototypes/buildings/pulp-mill-mk04"
require "prototypes/buildings/pcb-factory-mk01"
require "prototypes/buildings/pcb-factory-mk02"
require "prototypes/buildings/pcb-factory-mk03"
require "prototypes/buildings/pcb-factory-mk04"
require "prototypes/buildings/chipshooter-mk01"
require "prototypes/buildings/chipshooter-mk02"
require "prototypes/buildings/chipshooter-mk03"
require "prototypes/buildings/chipshooter-mk04"
require "prototypes/buildings/nano-assembler-mk01"
require "prototypes/buildings/nano-assembler-mk02"
require "prototypes/buildings/nano-assembler-mk03"
require "prototypes/buildings/nano-assembler-mk04"
require "prototypes/buildings/cadaveric-arum-mk01"
require "prototypes/buildings/quantum-computer"
require "prototypes/buildings/particle-accelerator-mk01"
require "prototypes/buildings/particle-accelerator-mk02"
require "prototypes/buildings/particle-accelerator-mk03"
require "prototypes/buildings/particle-accelerator-mk04"
require "prototypes/buildings/py-roboport-mk03"

if not mods["pyalienlife"] then
    require "prototypes/buildings/crashed-assembler-mk01"
end

--(( TRAINS ))--
require "prototypes/buildings/ht-locomotive/ht-locomotive"
require "prototypes/buildings/ht-locomotive/ht-generic-wagon"
require "prototypes/buildings/ht-locomotive/ht-generic-fluid-wagon"

--(( FLUIDS ))--
require "prototypes/fluids/fluids"

require "__pycoalprocessing__/prototypes/fluids/rare-earth-mud"

--(( FUEL VALUES ))--
data.raw.fluid["benzene"].fuel_value = "1MJ"
data.raw.fluid["ethylene"].fuel_value = "1MJ"
data.raw.fluid["methane"].fuel_value = "0.8MJ"
data.raw.fluid["propene"].fuel_value = "1MJ"
data.raw.fluid["tall-oil"].fuel_value = "1MJ"
