Recipe("electronic-circuit"):remove_unlock("electronics")
Recipe("basic-electronic-components"):remove_unlock("electronics")
Recipe("silicon-plate"):remove_unlock("basic-electronics")
Recipe("phenolic-board"):remove_unlock("advanced-electronics")
Recipe("circuit-board"):remove_unlock("advanced-electronics")
Recipe("advanced-circuit"):remove_unlock("advanced-electronics")
Recipe("advanced-logic-board"):remove_unlock("advanced-electronics-2")
Recipe("wooden-board"):set_enabled(false)
