-- TECH CHANGES
TECHNOLOGY("advanced-mining-facilities"):remove_prereq("electric-engine")
TECHNOLOGY('boron-2'):remove_prereq('helium-processing'):remove_pack('production-science-pack'):add_prereq("filtration-2")
TECHNOLOGY('helium-processing'):remove_prereq('fuel-production'):add_prereq('semiconductor-doping-2')
TECHNOLOGY('sc-unit'):add_prereq('re-tin'):add_prereq('ndfeb-alloy'):add_prereq('graphene')
TECHNOLOGY('ethanolamine'):remove_prereq('energy-2'):remove_prereq('super-alloy'):add_prereq('bio-machines')
TECHNOLOGY('fusion-mk01'):remove_prereq('boron-2')


-- RECIPE UNLOCKS
RECIPE('vacuum'):remove_unlock('advanced-mining-facilities'):add_unlock('vacuum-tube-electronics')
RECIPE('vacuum-pump-mk01'):remove_unlock('advanced-mining-facilities'):add_unlock('vacuum-tube-electronics')
RECIPE('centrifugal-pan-mk01'):remove_unlock('diamond-mining')
RECIPE('gas-separator-mk01'):remove_unlock('sc-unit'):remove_unlock('helium-processing-2')
RECIPE('pressured-air'):remove_unlock('helium-processing'):add_unlock('semiconductor-doping-2')
RECIPE('purified-air'):remove_unlock('helium-processing'):add_unlock('semiconductor-doping-2')
RECIPE('cool-air'):remove_unlock('helium-processing'):add_unlock('semiconductor-doping-2')
RECIPE('cold-clean-air'):remove_unlock('helium-processing'):add_unlock('semiconductor-doping-2')
RECIPE('liquid-pure-air'):remove_unlock('helium-processing'):add_unlock('semiconductor-doping-2')
RECIPE('agitator-mk01'):remove_unlock('advanced-mining-facilities')
RECIPE('mo-mine'):remove_unlock('molybdenum-processing'):add_unlock('intergrated-circuits-1')
RECIPE('thickener-mk01'):remove_unlock('advanced-mining-facilities')
RECIPE('pressured-water'):remove_unlock('xyhiphoe')
RECIPE('nenbit-matrix'):remove_unlock('production-science-pack')
RECIPE('nbti-alloy'):remove_unlock('production-science-pack')
RECIPE('nexelit-matrix'):remove_unlock('production-science-pack')
RECIPE('compressor-mk01'):remove_unlock('helium-processing')
RECIPE('silver-foam'):remove_unlock('fusion-mk03')
RECIPE('agzn-alloy'):remove_unlock('fusion-mk03')
RECIPE('sodium-chlorate'):remove_unlock('vanadium-processing'):add_unlock('filtration-2')
RECIPE('bio-reactor'):remove_unlock('ethanolamine')
RECIPE('genlab-mk01'):remove_unlock('ethanolamine')


-- RECIPE CHANGES
RECIPE('science-coating'):add_ingredient({type = 'item', name = 'nylon', amount = 5}):add_ingredient({type = 'item', name = 'zinc-acetate', amount = 15})
RECIPE('bio-reactor'):add_ingredient({type = 'item', name = 'advanced-circuit', amount = 5})
RECIPE('sc-coil'):add_ingredient({type = 'item', name = 're-tin', amount = 1})
RECIPE('coil-core'):add_ingredient({type = 'item', name = 'nexelit-plate', amount = 2})
RECIPE('magnetic-core'):add_ingredient({type = 'item', name = 'ndfeb-alloy', amount = 1}):add_ingredient({type = 'item', name = 'epoxy', amount = 1})
RECIPE('deposited-core'):change_category('nano')
RECIPE('boron-mixture'):replace_ingredient('helium', 'acetylene')
RECIPE('fusion-reactor-mk01'):replace_ingredient('advanced-circuit', 'processing-unit')
RECIPE('fusion-reactor-mk02'):replace_ingredient('advanced-circuit', 'intelligent-unit')
RECIPE('nexelit-matrix'):replace_ingredient('treated-wood', 'epoxy')
RECIPE('mixer-mk01'):add_ingredient({type = 'item', name = 'electronic-circuit', amount = 10})
RECIPE('kmauts-ration'):remove_ingredient("organics"):add_ingredient({type = "item", name = "skin", amount = 25})
RECIPE('kmauts-ration'):remove_ingredient("ralesia"):add_ingredient({type = "item", name = "blood-meal", amount = 5})
RECIPE('agitator-mk01'):replace_ingredient('plastic-bar', 'melamine')
