-- TECH CHANGES
TECHNOLOGY("advanced-mining-facilities"):remove_prereq("electric-engine")
TECHNOLOGY('boron-2'):remove_prereq('helium-processing'):remove_pack('production-science-pack'):add_prereq("filtration-2")
TECHNOLOGY('helium-processing'):remove_prereq('fuel-production'):add_prereq('semiconductor-doping-2')
TECHNOLOGY('sc-unit'):add_prereq('magnetic-core'):add_prereq('graphene')
TECHNOLOGY('ethanolamine'):remove_prereq('energy-2'):remove_prereq('super-alloy'):add_prereq('biotech')
TECHNOLOGY('fusion-mk01'):remove_prereq('boron-2')
TECHNOLOGY('filtration'):add_prereq('zipir')
TECHNOLOGY('nenbit-matrix'):add_prereq('epoxy')

-- RECIPE UNLOCKS
RECIPE('vacuum'):remove_unlock('advanced-mining-facilities'):add_unlock('vacuum-tube-electronics')
RECIPE('vacuum-pump-mk01'):remove_unlock('advanced-mining-facilities'):add_unlock('vacuum-tube-electronics')
RECIPE('centrifugal-pan-mk01'):remove_unlock('diamond-mining'):add_unlock("fluid-processing-machines-1")
RECIPE('pressured-air'):remove_unlock('helium-processing')
RECIPE('purified-air'):remove_unlock('helium-processing'):add_unlock('semiconductor-doping-2')
RECIPE('cool-air'):remove_unlock('helium-processing'):add_unlock('semiconductor-doping-2')
RECIPE('cold-clean-air'):remove_unlock('helium-processing'):add_unlock('semiconductor-doping-2')
RECIPE('liquid-pure-air'):remove_unlock('helium-processing'):add_unlock('semiconductor-doping-2')
RECIPE('mo-mine'):remove_unlock('molybdenum-processing'):add_unlock('integrated-circuits-1')
RECIPE('pressured-water'):remove_unlock('xyhiphoe')
RECIPE('compressor-mk01'):remove_unlock('helium-processing')
RECIPE('silver-foam'):remove_unlock('fusion-mk03')
RECIPE('agzn-alloy'):remove_unlock('fusion-mk03')
RECIPE('sodium-chlorate'):remove_unlock('vanadium-processing'):add_unlock('filtration-2')
RECIPE('bio-reactor'):remove_unlock('ethanolamine')
RECIPE('genlab-mk01'):remove_unlock('ethanolamine')
RECIPE('calcinate-separation'):remove_unlock('regolite-mining'):add_unlock('fluid-separation')
RECIPE('sc-wire'):remove_unlock('sc-unit')
RECIPE('coil-core'):remove_unlock('sc-unit')
RECIPE('sc-coil'):remove_unlock('sc-unit')
RECIPE('magnetic-core'):remove_unlock('sc-unit')
RECIPE("ferrite"):remove_unlock("sc-unit"):add_unlock("basic-electronics")
RECIPE("thickener-mk01"):remove_unlock("advanced-mining-facilities"):add_unlock("fluid-processing-machines-1")


-- RECIPE CHANGES
RECIPE('science-coating'):add_ingredient({type = 'item', name = 'nylon', amount = 5}):add_ingredient({type = 'item', name = 'zinc-acetate', amount = 15})
RECIPE('bio-reactor'):add_ingredient({type = 'item', name = 'advanced-circuit', amount = 5})
RECIPE('sc-coil'):add_ingredient({type = 'item', name = 're-tin', amount = 1})
RECIPE('coil-core'):add_ingredient({type = 'item', name = 'nexelit-plate', amount = 2})
RECIPE('magnetic-core'):add_ingredient({type = 'item', name = 'ndfeb-alloy', amount = 1}):add_ingredient({type = 'item', name = 'epoxy', amount = 1})
RECIPE('deposited-core'):change_category('nano')
RECIPE('boron-mixture'):replace_ingredient('helium', 'acetylene')
RECIPE('fusion-reactor-mk01'):replace_ingredient('advanced-circuit', 'processing-unit')
RECIPE('fusion-reactor-mk02'):replace_ingredient('advanced-circuit', 'intelligent-unit')
RECIPE('nexelit-matrix'):replace_ingredient('treated-wood', 'epoxy')
RECIPE('mixer-mk01'):add_ingredient({type = 'item', name = 'electronic-circuit', amount = 10})
RECIPE('kmauts-ration'):remove_ingredient("organics"):add_ingredient({type = "item", name = "skin", amount = 25})
RECIPE('kmauts-ration'):remove_ingredient("ralesia"):add_ingredient({type = "item", name = "blood-meal", amount = 5})
RECIPE('agitator-mk01'):replace_ingredient('plastic-bar', 'melamine')
RECIPE("centrifugal-pan-mk01"):replace_ingredient("advanced-circuit", "electronic-circuit")
